name: OpenFL
collections:
  showcase:
    output: true
    permalink: /showcase/title/:path/
defaults:
 - scope:
     path: ""
     type: showcase
   values:
     layout: showcase-item
 - scope:
     path: "showcase"
   values:
     layout: showcase
 - scope:
     path: ""
     type: posts
   values:
     layout: post
 - scope:
     path: "learn"
   values:
     layout: learn-sidebar
excerpt_separator: "<!--more-->"
plugins:
 - jekyll-feed
 - jekyll-optional-front-matter
 - jekyll-paginate
 - jekyll-redirect-from
 - jekyll-relative-links
 - jekyll-seo-tag
 - jekyll-sitemap
 - kramdown
highlighter: rouge
markdown: kramdown
paginate: 6
paginate_path: "blog/page/:num"
permalink: /blog/:year/:month/:day/:title/
redcarpet:
  extensions:
   - strikethrough
   - no_intra_emphasis
   - autolink
   - tables
   - with_toc_data
   - fenced_code_blocks
feed:
  path: blog/rss.xml
url: http://www.openfl.org
exclude: [ "node_modules", "README.md", "Gemfile", "Gemfile.lock", "package-lock.json" ]
emptyArray: []